apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hello-cd
  source:
    path: ./
    repoURL: https://github.com/lrhhhhhh/hello-deployments.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
