apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-pvc
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi
