apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-pvc
  namespace: hello
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: repo-pv
  namespace: hello
spec:
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: local-storage
  hostPath: 
    path: /mnt/data 
  
