apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-ci-sa 
  namespace: hello

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-trigger-binding
  namespace: hello
subjects:
- kind: ServiceAccount
  name: hello-ci-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hello-trigger-clusterbinding
  namespace: hello
subjects:
- kind: ServiceAccount
  name: hello-ci-sa
  namespace: hello
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
