---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-ci-sa # tekton bulid sa
secrets:
  - name: github-auth
  - name: github-secret

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: tekton-clusterrole-binding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-admin
# subjects:
#   - kind: ServiceAccount
#     name: hello-ci-sa
#     namespace: tekton-pipelines


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-trigger-binding
subjects:
- kind: ServiceAccount
  name: hello-ci-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hello-trigger-clusterbinding
subjects:
- kind: ServiceAccount
  name: hello-ci-sa
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
