---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hello-listener
  namespace: hello
spec:
  serviceAccountName: hello-ci-sa
  triggers:
    - name: hello-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
            - name: "addChangedFiles"
              value:
                enabled: true
      bindings:
        - ref: hello-binding
      template:
        ref: hello-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: hello-ci-sa
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: hello-binding
  namespace: hello
spec:
  params:
    - name: changedfiles
      value: $(extensions.changed_files)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: hello-template
  namespace: hello
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: gitlab-run-
      spec:
        podTemplate:
          securityContext:
            fsGroup: 65532
        serviceAccountName: hello-ci-sa
        pipelineRef:
          name: hello-pipeline
        workspaces:
          - name: output
            persistentVolumeClaim:
              claimName: repo-pvc
          - name: docker-credentials
            secret:
              secretName: docker-credentials
          - name: ssh-secret
            secret:
              secretName: ssh-secret
        params:
          - name: git_url
            value: $(tt.params.gitrepositoryurl)
          - name: git_infra_url
            value: xxx
          - name: REVISION
            value: ""
